"""
Member 4: Post-Extraction Intelligence & Presentation Layer.
Phase 1: Data Contract & Boundary Definitions.
Phase 2: Validation & Normalization Layer.
Phase 3: Contextual Task Intelligence Engine.
Phase 4: Priority Intelligence Engine.
Phase 5: Confidence Intelligence Engine.
"""

from .schemas import (
    Member4Input,
    Member4ActionItemInput,
    Member4DecisionInput,
    Member4Output,
    Member4ActionItemOutput,
    Member4DecisionOutput,
    Member2TranscriptSegment,
    Member2TopicContextInput,
    PriorityLevel,
    ReviewPriority,
    PriorityExplanation,
    ConfidenceBreakdown,
    TriageStatus,
    TaskContext,
    TopicContextStatus,
    NormalizedActionItem,
    NormalizedDecision,
    Member4NormalizedOutput,
    LocalizedDialogueContext,
    RelatedDecisionContext,
    ContextRichActionItem,
    ContextRichDecision,
    Member4ContextOutput,
    PriorityFactorContribution,
    PriorityAssessment,
    PriorityEnrichedActionItem,
    Member4PriorityOutput,
    ConfidenceLevel,
    ConfidenceFactorContribution,
    ConfidenceAssessment,
    ConfidenceEnrichedActionItem,
    Member4ConfidenceOutput,
    ReviewStatus,
    ReviewReasonCode,
    ReviewDecision,
    TriageEnrichedActionItem,
    Member4TriageOutput,
    ExplanationFactor,
    EvidenceReference,
    PriorityExplainability,
    ConfidenceExplainability,
    ReviewExplainability,
    ActionItemExplanation,
    ExplainedActionItem,
    Member4ExplainedOutput,
    UserRole,
    RoleEmphasis,
    PersonalizedActionItem,
    PersonalizedViewFilter,
    PersonalizedMeetingView,
    SpeakerIdentity,
)

from .speaker_resolver import (
    detect_explicit_self_id,
    resolve_meeting_speakers,
    format_speaker_display,
)
from .normalizer import normalize_member3_input
from .context_engine import build_task_context
from .priority_engine import infer_task_priorities, PriorityModelConfig, DEFAULT_CONFIG
from .confidence_engine import (
    infer_task_confidence,
    ConfidenceModelConfig,
    DEFAULT_CONFIDENCE_CONFIG,
)
from .review_engine import (
    evaluate_task_triage,
    triage_action_items,
    ReviewModelConfig,
    DEFAULT_REVIEW_CONFIG,
)
from .explainability_engine import (
    rank_explanation_factors,
    explain_priority,
    explain_confidence,
    explain_review,
    extract_evidence_traces,
    explain_action_item,
    explain_meeting_triage,
)
from .personalization_engine import (
    build_role_emphasis,
    project_action_item,
    sort_personalized_items,
    filter_personalized_items,
    build_role_headline,
    personalize_meeting_view,
)

__all__ = [
    "Member4Input",
    "Member4ActionItemInput",
    "Member4DecisionInput",
    "Member4Output",
    "Member4ActionItemOutput",
    "Member4DecisionOutput",
    "Member2TranscriptSegment",
    "Member2TopicContextInput",
    "PriorityLevel",
    "ReviewPriority",
    "PriorityExplanation",
    "ConfidenceBreakdown",
    "TriageStatus",
    "TaskContext",
    "TopicContextStatus",
    "NormalizedActionItem",
    "NormalizedDecision",
    "Member4NormalizedOutput",
    "LocalizedDialogueContext",
    "RelatedDecisionContext",
    "ContextRichActionItem",
    "ContextRichDecision",
    "Member4ContextOutput",
    "PriorityFactorContribution",
    "PriorityAssessment",
    "PriorityEnrichedActionItem",
    "Member4PriorityOutput",
    "ConfidenceLevel",
    "ConfidenceFactorContribution",
    "ConfidenceAssessment",
    "ConfidenceEnrichedActionItem",
    "Member4ConfidenceOutput",
    "ReviewStatus",
    "ReviewReasonCode",
    "ReviewDecision",
    "TriageEnrichedActionItem",
    "Member4TriageOutput",
    "ExplanationFactor",
    "EvidenceReference",
    "PriorityExplainability",
    "ConfidenceExplainability",
    "ReviewExplainability",
    "ActionItemExplanation",
    "ExplainedActionItem",
    "Member4ExplainedOutput",
    "UserRole",
    "RoleEmphasis",
    "PersonalizedActionItem",
    "PersonalizedViewFilter",
    "PersonalizedMeetingView",
    "SpeakerIdentity",
    "detect_explicit_self_id",
    "resolve_meeting_speakers",
    "format_speaker_display",
    "normalize_member3_input",
    "build_task_context",
    "infer_task_priorities",
    "PriorityModelConfig",
    "DEFAULT_CONFIG",
    "infer_task_confidence",
    "ConfidenceModelConfig",
    "DEFAULT_CONFIDENCE_CONFIG",
    "evaluate_task_triage",
    "triage_action_items",
    "ReviewModelConfig",
    "DEFAULT_REVIEW_CONFIG",
    "rank_explanation_factors",
    "explain_priority",
    "explain_confidence",
    "explain_review",
    "extract_evidence_traces",
    "explain_action_item",
    "explain_meeting_triage",
    "build_role_emphasis",
    "project_action_item",
    "sort_personalized_items",
    "filter_personalized_items",
    "build_role_headline",
    "personalize_meeting_view",
]







